<!DOCTYPE html>
<html lang="en-us">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Source Themes Academic 4.7.0">

  

  
  
  
  
  
    
    
    
  
  

  <meta name="author" content="Matthew Reusswig">

  
  
  
    
  
  <meta name="description" content="Recently, I was working with some netCDF files with raster time-series data in a conic projection. I was doing some calculations with the data and wished to plot the results as a map. The problem was the data file did not include latitude/longitude data for the pixels or a coordinate reference system (crs). The file included metadata which could be used to puzzle out a crs for the xy-indexed grid, but it wasn’t directly readable by any of the R packages I tried, nor did my attempt to build an appropriate proj4 string work out.">

  
  <link rel="alternate" hreflang="en-us" href="/post/use-stars-to-visualize-curvilinear-netcdf-rasters/">

  


  
  
  
  <meta name="theme-color" content="#4caf50">
  

  
  
  
  <script src="/js/mathjax-config.js"></script>
  

  
  
  
  
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/academicons/1.8.6/css/academicons.min.css" integrity="sha256-uFVgMKfistnJAfoCUQigIl+JfUaP47GrRKjf6CTPVmw=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-1/css/all.min.css" integrity="sha256-4w9DunooKSr3MFXHXWyFER38WmPdm361bQS/2KUWZbU=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css" integrity="sha256-Vzbj7sDDS/woiFS3uNKo8eIuni59rjyNGtXfstRzStA=" crossorigin="anonymous">

    
    
    
      
    
    
      
      
        
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/styles/github.min.css" crossorigin="anonymous" title="hl-light">
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/styles/dracula.min.css" crossorigin="anonymous" title="hl-dark" disabled>
        
      
    

    

    

    
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
        <script src="https://cdnjs.cloudflare.com/ajax/libs/lazysizes/5.1.2/lazysizes.min.js" integrity="sha256-Md1qLToewPeKjfAHU1zyPwOutccPAm5tahnaw7Osw0A=" crossorigin="anonymous" async></script>
      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
        <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js" integrity="" crossorigin="anonymous" async></script>
      
    
      

      
      

      
    

  

  
  
  
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,700%7CRoboto:400,400italic,700%7CRoboto+Mono&display=swap">
  

  
  
  
  
  <link rel="stylesheet" href="/css/academic.css">

  




  


  

  <link rel="manifest" href="/index.webmanifest">
  <link rel="icon" type="image/png" href="/images/icon_hu0b7a4cb9992c9ac0e91bd28ffd38dd00_9727_32x32_fill_lanczos_center_2.png">
  <link rel="apple-touch-icon" type="image/png" href="/images/icon_hu0b7a4cb9992c9ac0e91bd28ffd38dd00_9727_192x192_fill_lanczos_center_2.png">

  <link rel="canonical" href="/post/use-stars-to-visualize-curvilinear-netcdf-rasters/">

  
  
  
  
  
    
    
  
  
  <meta property="twitter:card" content="summary">
  
  <meta property="og:site_name" content="Matthew Reusswig&#39;s Home Page">
  <meta property="og:url" content="/post/use-stars-to-visualize-curvilinear-netcdf-rasters/">
  <meta property="og:title" content="Using Stars and R to Visualize Curvilinear NetCDF Rasters | Matthew Reusswig&#39;s Home Page">
  <meta property="og:description" content="Recently, I was working with some netCDF files with raster time-series data in a conic projection. I was doing some calculations with the data and wished to plot the results as a map. The problem was the data file did not include latitude/longitude data for the pixels or a coordinate reference system (crs). The file included metadata which could be used to puzzle out a crs for the xy-indexed grid, but it wasn’t directly readable by any of the R packages I tried, nor did my attempt to build an appropriate proj4 string work out."><meta property="og:image" content="img/map[gravatar:%!s(bool=false) shape:circle]">
  <meta property="twitter:image" content="img/map[gravatar:%!s(bool=false) shape:circle]"><meta property="og:locale" content="en-us">
  
    
      <meta property="article:published_time" content="2020-04-26T00:00:00&#43;00:00">
    
    <meta property="article:modified_time" content="2020-04-26T11:12:47-04:00">
  

  


    






  




<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "BlogPosting",
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "/post/use-stars-to-visualize-curvilinear-netcdf-rasters/"
  },
  "headline": "Using Stars and R to Visualize Curvilinear NetCDF Rasters",
  
  "datePublished": "2020-04-26T00:00:00Z",
  "dateModified": "2020-04-26T11:12:47-04:00",
  
  "author": {
    "@type": "Person",
    "name": "Matthew Reusswig"
  },
  
  "publisher": {
    "@type": "Organization",
    "name": "Matthew Reusswig's Home Page",
    "logo": {
      "@type": "ImageObject",
      "url": "/images/icon_hu0b7a4cb9992c9ac0e91bd28ffd38dd00_9727_192x192_fill_lanczos_center_2.png"
    }
  },
  "description": "Recently, I was working with some netCDF files with raster time-series data in a conic projection. I was doing some calculations with the data and wished to plot the results as a map. The problem was the data file did not include latitude/longitude data for the pixels or a coordinate reference system (crs). The file included metadata which could be used to puzzle out a crs for the xy-indexed grid, but it wasn’t directly readable by any of the R packages I tried, nor did my attempt to build an appropriate proj4 string work out."
}
</script>

  

  


  


  





  <title>Using Stars and R to Visualize Curvilinear NetCDF Rasters | Matthew Reusswig&#39;s Home Page</title>

</head>

<body id="top" data-spy="scroll" data-offset="70" data-target="#TableOfContents" >

  <aside class="search-results" id="search">
  <div class="container">
    <section class="search-header">

      <div class="row no-gutters justify-content-between mb-3">
        <div class="col-6">
          <h1>Search</h1>
        </div>
        <div class="col-6 col-search-close">
          <a class="js-search" href="#"><i class="fas fa-times-circle text-muted" aria-hidden="true"></i></a>
        </div>
      </div>

      <div id="search-box">
        
        
        
      </div>

    </section>
    <section class="section-search-results">

      <div id="search-hits">
        
      </div>

    </section>
  </div>
</aside>


  







<nav class="navbar navbar-expand-lg navbar-light compensate-for-scrollbar" id="navbar-main">
  <div class="container">

    
    <div class="d-none d-lg-inline-flex">
      <a class="navbar-brand" href="/">Matthew Reusswig&#39;s Home Page</a>
    </div>
    

    
    <button type="button" class="navbar-toggler" data-toggle="collapse"
            data-target="#navbar-content" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
    <span><i class="fas fa-bars"></i></span>
    </button>
    

    
    <div class="navbar-brand-mobile-wrapper d-inline-flex d-lg-none">
      <a class="navbar-brand" href="/">Matthew Reusswig&#39;s Home Page</a>
    </div>
    

    
    
    <div class="navbar-collapse main-menu-item collapse justify-content-end" id="navbar-content">

      
      <ul class="navbar-nav d-md-inline-flex">
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#about"><span>About</span></a>
        </li>

        
        

        

        
        
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#cv"><span>Resumé</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#publications"><span>Reports & Articles</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#posts"><span>Notes & Mutterings</span></a>
        </li>

        
        

      

        
      </ul>
    </div>

    <ul class="nav-icons navbar-nav flex-row ml-auto d-flex pl-md-2">
      

      

      

    </ul>

  </div>
</nav>


  <article class="article">

  












  

  
  
  
<div class="article-container pt-3">
  <h1>Using Stars and R to Visualize Curvilinear NetCDF Rasters</h1>

  

  
    


<div class="article-metadata">

  
  

  
  <span class="article-date">
    
    
      
          Last updated on
      
    
    Apr 26, 2020
  </span>
  

  

  

  
  
  

  
  

</div>

    














  
</div>



  <div class="article-container">

    <div class="article-style">
      


<p>Recently, I was working with some netCDF files with raster time-series data in a conic projection. I was doing some calculations with the data and wished to plot the results as a map. The problem was the data file did not include latitude/longitude data for the pixels or a coordinate reference system (crs). The file included metadata which could be used to puzzle out a crs for the xy-indexed grid, but it wasn’t directly readable by any of the R packages I tried, nor did my attempt to build an appropriate proj4 string work out. However, the latitude/longitude coordinates for the pixels were stored in a separate netCDF file but I had a heck of time marrying the data and coordinate files together. This post documents the process I puzzled out and is largely based on <a href="https://gis.stackexchange.com/questions/321144/convert-xyz-to-stars-curvilinear-grid-and-plot">this stackoverflow discussion</a>.</p>
<p>Stars is used to read in the netCDF files. Stars and dplyr are used to manipulate the data. Viridis and ggplot2 are used for plotting. Finally, a couple of shapefiles will be pulled from rnaturalearth to provide geographic context to the raster.</p>
<pre class="r"><code>library(stars)
library(viridis)
library(dplyr)
library(ggplot2)
library(rnaturalearth)</code></pre>
<p>The data file (“T_LAKE3D.daily.1970.nc”) and the lat/lon file (“Z_LAKE3D.XLONGXLAT.nc”) are read into memory using stars::read_ncdf. Printing the stored objects shows what data is stored in each and what dimensionality it has. Note that stars does not automatically read in all the available variables in a file, so I have specified the relevant variables in this instance.</p>
<pre class="r"><code>## Note: Local paths to data read-in elsewhere.
sst &lt;- read_ncdf(path_to_data_file, var = c(&quot;T_LAKE3D&quot;))</code></pre>
<pre><code>## Warning in nc_coord_var_finder(dim, var, att, axe, v): missing coordinate
## variables names in coordinates attribute trying to find non-auxiliary coordinate
## variables.</code></pre>
<pre><code>## Warning in .get_nc_projection(meta$attribute, rep_var, all_coord_var): No
## projection information found in nc file.</code></pre>
<pre><code>## Warning: ignoring unrecognized unit: k</code></pre>
<pre class="r"><code>cf  &lt;- read_ncdf(path_to_coord_file, var = c(&quot;XLAT&quot;, &quot;XLONG&quot;))</code></pre>
<pre><code>## Warning in .get_nc_projection(meta$attribute, rep_var, all_coord_var): No
## projection information found in nc file.</code></pre>
<pre class="r"><code>sst</code></pre>
<pre><code>## stars object with 4 dimensions and 1 attribute
## attribute(s), summary of first 1e+05 cells:
##    T_LAKE3D      
##  Min.   :-999.0  
##  1st Qu.:-999.0  
##  Median :-999.0  
##  Mean   :-949.4  
##  3rd Qu.:-999.0  
##  Max.   : 277.0  
## dimension(s):
##                                 from  to offset delta refsys point values    
## west_east                          1 111    0.5     1     NA    NA   NULL [x]
## south_north                        1  78    0.5     1     NA    NA   NULL [y]
## soil_levels_or_lake_levels_stag    1  10    0.5     1     NA    NA   NULL    
## Time                               1 365    0.5     1     NA    NA   NULL</code></pre>
<pre class="r"><code>cf</code></pre>
<pre><code>## stars object with 3 dimensions and 2 attributes
## attribute(s):
##     XLAT [°]       XLONG [°]      
##  Min.   :32.62   Min.   :-110.89  
##  1st Qu.:38.93   1st Qu.: -95.90  
##  Median :44.29   Median : -85.00  
##  Mean   :44.30   Mean   : -85.00  
##  3rd Qu.:49.66   3rd Qu.: -74.10  
##  Max.   :55.70   Max.   : -59.11  
## dimension(s):
##             from  to offset delta refsys point values    
## west_east      1 111    0.5     1     NA    NA   NULL [x]
## south_north    1  78    0.5     1     NA    NA   NULL [y]
## Time           1   1     NA    NA     NA    NA      1</code></pre>
<p>The data stored in sst is water temperature data labeled “T_LAKE3D” in degrees kelvin with xy grid index dimensions (“west_east” and “south_north”), lake depth of the temperature estimate (“soil_levels_or_lake_levels_stag”) and time in days (“Time”). So this file contains 365 x 10 raster images–one for each day of the year at each of the ten depth layers.</p>
<p>The object cf stores latitude (“XLAT”) longitude (“XLONG”) in degrees with dimensions for the xy grid and, technically, time (there’s only 1 day in that dimension).</p>
<p>When reading in the data we can also specify how stars should read in the dimensions. For example, we can choose to read in data for a single day at a single depth. Let’s read in the data for January 1st (Time 1) at the lake bottom (depth level 10) using the ncsub option.</p>
<pre class="r"><code>sst &lt;- read_ncdf(path_to_data_file, var = c(&quot;T_LAKE3D&quot;), 
## Specify the layers to read in by dimension. Dimension 3 corresponds to lake 
## depth with 10 layers. We&#39;ll use layer 10 since its at the lake bottom.
## Dimension 4 is time in days (listed as an index from 1 to 365). We&#39;ll grab
## day 1 and read it into memory.
                 ncsub = cbind(start = c(1, 1, 10, 1), count = c(111, 78, 1, 1)))</code></pre>
<p>This image is in a conic projection where each pixel has equal area, so the lat/lon coordinates do not form a rectilinear grid–instead they form a curved shape. This can be seen when visualizing the lat and lon values.</p>
<pre class="r"><code>plot(cf[1])</code></pre>
<p><img src="/post/2020-04-26-using-stars-to-visualize-curvilinear-netcdf-rasters_files/figure-html/plot%20lat%20and%20lon%20values-1.png" width="672" /></p>
<pre class="r"><code>plot(cf[2])</code></pre>
<p><img src="/post/2020-04-26-using-stars-to-visualize-curvilinear-netcdf-rasters_files/figure-html/plot%20lat%20and%20lon%20values-2.png" width="672" /></p>
<p>Stars has options within the read_* functions for specifying a curvilinear raster. When the lat/lon coordinates are within the data file, one can use the option “curvilinear” to point the function to them. However, in this case, the coordinates are in an external file. The method for overcoming this difficulty is to instead use the function stars::st_as_stars and to point the option “curvilinear” to a pair of matrices storing the lat/lon coordinates. The matrices need to have the same xy dimensionality as the data raster. So, in this case, extract the values “XLAT” and “XLONG” in the object cf and covert them to matrices with the same dimensions as the temperature data. The temperature data grid has 111 columns and 78 rows.</p>
<pre class="r"><code>## Convert the lat lon coordinates into matrices with the same dimensions as the 
## raster data.
x = matrix(cf[[1]], 111, 78)
y = matrix(cf[[2]], 111, 78)</code></pre>
<p>Next, convert the temperature data with the curvilinear coordinates specified using stars::st_as_stars. We don’t directly use the stars::read_* functions becasue they don’t seem to like be given external curvilinear matrices (or more likely, I was doing something wrong), but st_as_stars handles them just fine.</p>
<p>The curvilinear option needs to be fed a list that assigns the coordinate matrices to the proper dimension variables in the data file–e.g., list(&lt;column_dimension_name&gt; = &lt;latitude_matrix_object&gt;, &lt;row_dimension_name&gt; = &lt;longitude_matrix_object&gt;). Observe that the dimension labels don’t require quotes.</p>
<pre class="r"><code>sst &lt;- st_as_stars(sst,
                 curvilinear = list(west_east = y, south_north = x))

sst</code></pre>
<pre><code>## stars object with 4 dimensions and 1 attribute
## attribute(s):
##    T_LAKE3D    
##  Min.   :-999  
##  1st Qu.:-999  
##  Median :-999  
##  Mean   :-949  
##  3rd Qu.:-999  
##  Max.   : 277  
## dimension(s):
##                                 from  to offset delta    refsys point
## west_east                          1 111     NA    NA EPSG:4326    NA
## south_north                        1  78     NA    NA EPSG:4326    NA
## soil_levels_or_lake_levels_stag    1   1     NA    NA        NA    NA
## Time                               1   1     NA    NA        NA    NA
##                                                       values    
## west_east                        [111x78] -110.89,...,-59.11 [x]
## south_north                     [111x78] 32.6199,...,55.7044 [y]
## soil_levels_or_lake_levels_stag                           10    
## Time                                                       1    
## curvilinear grid</code></pre>
<p>The data object is now marked as curvilinear and the lat/lon coordinates have been associated with the “west_east” and “south_north” dimensions.</p>
<p>Finally, stars allows one to clean/manipulate data using dplyr operations and magrittr piping. Missing or masked values (e.g., land pixels) are stored as “-999” so we’ll replace those with NA values. I will also convert temperatures from degrees K to degrees C.</p>
<pre class="r"><code>sst &lt;- sst %&gt;% 
  ## Create a copy of the temperature variable renamed temp, then use select to 
  ## drop the original variable as an awkward way to rename the variable.
  mutate(temp = T_LAKE3D) %&gt;% 
  select(temp) %&gt;% 
  
  ## Replace the mask values (-999) with NA.
  mutate(temp = ifelse(temp == -999, NA, temp),
  
  ## Convert temp from degrees K to degrees C.       
         temp = temp - 273.15)
  
sst</code></pre>
<pre><code>## stars object with 4 dimensions and 1 attribute
## attribute(s):
##      temp         
##  Min.   :-11.153  
##  1st Qu.: -0.440  
##  Median :  3.379  
##  Mean   :  0.574  
##  3rd Qu.:  3.850  
##  Max.   :  3.850  
##  NA&#39;s   :8318     
## dimension(s):
##                                 from  to offset delta    refsys point
## west_east                          1 111     NA    NA EPSG:4326    NA
## south_north                        1  78     NA    NA EPSG:4326    NA
## soil_levels_or_lake_levels_stag    1   1     NA    NA        NA    NA
## Time                               1   1     NA    NA        NA    NA
##                                                       values    
## west_east                        [111x78] -110.89,...,-59.11 [x]
## south_north                     [111x78] 32.6199,...,55.7044 [y]
## soil_levels_or_lake_levels_stag                           10    
## Time                                                       1    
## curvilinear grid</code></pre>
<p>The data summary of temp in the sst object is now much more helpful without the numeric mask values distorting it. It will also plot better without the -999 values.</p>
<p>I’ll plot the temp data in ggplot using stars::geom_stars and add in some national boundaries and lake polygons to provide geographic context to the data. I’ll use the viridis package for the temperature color scale.</p>
<pre class="r"><code>## Since we have the coordinates, we&#39;ll use lat/lon values as crs.
st_crs(sst) &lt;- &quot;+proj=longlat +ellps=WGS84 +no_defs&quot;

## Load contextual map data
world &lt;- rnaturalearth::ne_countries(scale = &quot;medium&quot;, returnclass = &quot;sf&quot;)
lakes &lt;- rnaturalearth::ne_download(scale = &quot;medium&quot;, type = &#39;lakes&#39;, category = &#39;physical&#39;,
                                    returnclass = &quot;sf&quot;)</code></pre>
<pre><code>## OGR data source with driver: ESRI Shapefile 
## Source: &quot;C:\Users\Lamp\AppData\Local\Temp\Rtmpucrzt8&quot;, layer: &quot;ne_50m_lakes&quot;
## with 275 features
## It has 35 fields
## Integer64 fields read as strings:  scalerank ne_id</code></pre>
<pre class="r"><code>## Make sure the crs values are shared by all the mapped objects.
sst &lt;- st_transform(sst, st_crs(world))

## Plot your map
ggplot()  + 
  geom_sf(data = world, color = &quot;black&quot;, fill = &quot;white&quot;) + 
  geom_sf(data = lakes, color = &quot;black&quot;, fill = NA) +
  geom_stars(data = sst, alpha = 0.75) +
  coord_sf(ylim = c(41, 55), xlim = c(-105, -65)) +
  scale_fill_viridis() +
  theme(panel.border = element_rect(colour = &quot;black&quot;, fill = NA))</code></pre>
<p><img src="/post/2020-04-26-using-stars-to-visualize-curvilinear-netcdf-rasters_files/figure-html/plot%201-1.png" width="672" /></p>
<p>The data can also be visualized with base R plot.</p>
<pre class="r"><code>plot(st_geometry(world), axes = TRUE, ylim = c(41, 55), xlim = c(-105, -65))
plot(st_geometry(lakes), add = TRUE)
raster::plot(sst, as_points = FALSE, breaks = &quot;equal&quot;, col = topo.colors(100), 
     border = NA, key.pos = 1, add = TRUE)</code></pre>
<p><img src="/post/2020-04-26-using-stars-to-visualize-curvilinear-netcdf-rasters_files/figure-html/unnamed-chunk-1-1.png" width="672" /></p>

    </div>

    







<div class="share-box" aria-hidden="true">
  <ul class="share">
    
      
      
      
        
      
      
      
      <li>
        <a href="https://twitter.com/intent/tweet?url=/post/use-stars-to-visualize-curvilinear-netcdf-rasters/&amp;text=Using%20Stars%20and%20R%20to%20Visualize%20Curvilinear%20NetCDF%20Rasters" target="_blank" rel="noopener" class="share-btn-twitter">
          <i class="fab fa-twitter"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://www.facebook.com/sharer.php?u=/post/use-stars-to-visualize-curvilinear-netcdf-rasters/&amp;t=Using%20Stars%20and%20R%20to%20Visualize%20Curvilinear%20NetCDF%20Rasters" target="_blank" rel="noopener" class="share-btn-facebook">
          <i class="fab fa-facebook"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="mailto:?subject=Using%20Stars%20and%20R%20to%20Visualize%20Curvilinear%20NetCDF%20Rasters&amp;body=/post/use-stars-to-visualize-curvilinear-netcdf-rasters/" target="_blank" rel="noopener" class="share-btn-email">
          <i class="fas fa-envelope"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://www.linkedin.com/shareArticle?url=/post/use-stars-to-visualize-curvilinear-netcdf-rasters/&amp;title=Using%20Stars%20and%20R%20to%20Visualize%20Curvilinear%20NetCDF%20Rasters" target="_blank" rel="noopener" class="share-btn-linkedin">
          <i class="fab fa-linkedin-in"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://web.whatsapp.com/send?text=Using%20Stars%20and%20R%20to%20Visualize%20Curvilinear%20NetCDF%20Rasters%20/post/use-stars-to-visualize-curvilinear-netcdf-rasters/" target="_blank" rel="noopener" class="share-btn-whatsapp">
          <i class="fab fa-whatsapp"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://service.weibo.com/share/share.php?url=/post/use-stars-to-visualize-curvilinear-netcdf-rasters/&amp;title=Using%20Stars%20and%20R%20to%20Visualize%20Curvilinear%20NetCDF%20Rasters" target="_blank" rel="noopener" class="share-btn-weibo">
          <i class="fab fa-weibo"></i>
        </a>
      </li>
    
  </ul>
</div>












  






  
  
  
    
  
  
  
  <div class="media author-card content-widget-hr">
    
      
      <img class="avatar mr-3 avatar-circle" src="/authors/admin/avatar_hu136d63d6681ae1366f077ae890ab068e_245117_270x270_fill_q90_lanczos_center.jpg" alt="Avatar">
    

    <div class="media-body">
      <h5 class="card-title"><a href="/">Matthew Reusswig</a></h5>
      <h6 class="card-subtitle">Environmental Scientist and Engineer</h6>
      <p class="card-text">I am an environmental engineer and scientist specializing in NPDES program implementation, wastewater treatment, and watershed pollutant transport modeling.</p>
      <ul class="network-icon" aria-hidden="true">
  
    
    
    
      
    
    
    
    
    
    <li>
      <a href="mailto:matt.reusswig@gmail.com" >
        <i class="fas fa-envelope"></i>
      </a>
    </li>
  
</ul>

    </div>
  </div>









  
  



  </div>
</article>

      

    
    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.4/imagesloaded.pkgd.min.js" integrity="sha256-lqvxZrPLtfffUl2G/e7szqSvPBILGbwmsGE1MKlOi0Q=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.6/isotope.pkgd.min.js" integrity="sha256-CBrpuqrMhXwcLLUd5tvQ4euBHCdh7wGlDfNz8vbu/iI=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js" integrity="sha256-yt2kYMy0w8AbtF89WXb2P1rfjcP/HTHLT7097U8Y5b8=" crossorigin="anonymous"></script>

      
        <script src="https://cdnjs.cloudflare.com/ajax/libs/mermaid/8.4.4/mermaid.min.js" integrity="sha256-JEqEejGt4tR35L0a1zodzsV0/PJ6GIf7J4yDtywdrH8=" crossorigin="anonymous" title="mermaid"></script>
      

      
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/highlight.min.js" integrity="sha256-1zu+3BnLYV9LdiY85uXMzii3bdrkelyp37e0ZyTAQh0=" crossorigin="anonymous"></script>
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/languages/r.min.js"></script>
        
      

    

    
    

    
    
    <script>const code_highlighting = true;</script>
    

    
    
    <script>const isSiteThemeDark = false;</script>
    

    

    
    

    

    
    

    
    

    
    

    
    
    
    
    
    
    
    
    
    
    
    
    <script src="/js/academic.min.c97b94000ee75a76d9bc08f5a2e44814.js"></script>

    






  
  
  <div class="container">
    <footer class="site-footer">
  
  <p class="powered-by">
    
      <a href="/privacy/">Privacy Policy</a>
    
    
       &middot; 
      <a href="/terms/">Terms</a>
    
  </p>
  

  <p class="powered-by">
    © 2020 &middot; 

    Powered by the
    <a href="https://sourcethemes.com/academic/" target="_blank" rel="noopener">Academic theme</a> for
    <a href="https://gohugo.io" target="_blank" rel="noopener">Hugo</a>.

    
    <span class="float-right" aria-hidden="true">
      <a href="#" class="back-to-top">
        <span class="button_icon">
          <i class="fas fa-chevron-up fa-2x"></i>
        </span>
      </a>
    </span>
    
  </p>
</footer>

  </div>
  

  
<div id="modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Cite</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <pre><code class="tex hljs"></code></pre>
      </div>
      <div class="modal-footer">
        <a class="btn btn-outline-primary my-1 js-copy-cite" href="#" target="_blank">
          <i class="fas fa-copy"></i> Copy
        </a>
        <a class="btn btn-outline-primary my-1 js-download-cite" href="#" target="_blank">
          <i class="fas fa-download"></i> Download
        </a>
        <div id="modal-error"></div>
      </div>
    </div>
  </div>
</div>

</body>
</html>
